function param = parameterInfo

% Copyright 2014 The MathWorks, Inc.

param = [...
  nnetParamInfo('regularization','Regularization Ratio','nntype.real_0_to_1',0,...
  'Fraction of performance associated with regularization.'),...
  nnetParamInfo('normalization','Normalization','nntype.error_norm_mode','none',...
  'The kind of error normalization relative to target ranges.'),...
  nnetParamInfo('L2WeightRegularization','L2 Weight Regularization Coefficient','nntype.real_scalar',0,...
  'Coefficient which is used to weight the L2 regulariser.'),...
  nnetParamInfo('sparsityRegularization','Sparsity Regularization Coefficient','nntype.real_scalar',0,...
  'Coefficient which is used to weight the sparsity regulariser.'),...
  nnetParamInfo('sparsity','Desired Sparsity','nntype.real_0_to_1',0,...
  'Desired average percentage of neurons firing in first layer.'),...
  ];
